import { h } from 'preact';

export const validatorsRegExpValidatorDescription = (
  <>
    <p>This demo shows how JET's RegExpValidator can be used with Oracle JET editable components.</p>

    <h2>Test Steps</h2>
    <ol>
      <li>
        To see the error text generated by regExp validator enter an incorrect value. For example, if
        the field's pattern requires 3 or more numbers or letters, then type 'ab' and tab off the field.
      </li>
      <li>
        Enter a valid value in the expected pattern and tab off to clear error. For example, type 'abc'
        and tab off the field.
      </li>
    </ol>
  </>
);
