/**
  Copyright (c) 2015, 2026, Oracle and/or its affiliates.
  Licensed under The Universal Permissive License (UPL), Version 1.0
  as shown at https://oss.oracle.com/licenses/upl/

*/
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

const resizeObserverLoopMessages = new Set([
  'ResizeObserver loop completed with undelivered notifications.',
  'ResizeObserver loop limit exceeded'
]);

function isResizeObserverLoopError(error) {
  const message = typeof error === 'string' ? error : error && error.message;
  return resizeObserverLoopMessages.has(message);
}

class EnsureRedwoodThemeFirstPlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap('EnsureRedwoodThemeFirstPlugin', (compilation) => {
      HtmlWebpackPlugin.getHooks(compilation).beforeEmit.tap(
        'EnsureRedwoodThemeFirstPlugin',
        (data) => {
          const redwoodLegacyThemeHref = '/styles/redwood/20.1.2/web/redwood.css';
          const redwoodPreactThemeHref = '/styles/theme-redwood/20.1.2/web/theme.css';
          const redwoodThemeLinks = [
            `<link href="${redwoodLegacyThemeHref}" id="themestyle" rel="stylesheet">`,
            `<link href="${redwoodPreactThemeHref}" id="redwoodbase" rel="stylesheet">`,
            `<link href="/styles/app.css" id="appbase" rel="stylesheet">`
          ].join('\n    ');

          data.html = data.html
            .replace(
              /<!--\s*<link[^>]+(?:theme-redwood\/20\.1\.2\/web\/theme\.css|redwood\/20\.1\.2\/web\/redwood\.css)[^>]*>\s*-->\s*/g,
              ''
            )
            .replace(/<link[^>]+redwood\/20\.1\.2\/web\/redwood\.css[^>]*>\s*/g, '')
            .replace(/<link[^>]+theme-redwood\/20\.1\.2\/web\/theme\.css[^>]*>\s*/g, '');

          data.html = data.html.replace(/(<head[^>]*>)/i, `$1\n    ${redwoodThemeLinks}`);
          return data;
        }
      );
    });
  }
}

module.exports = {
  /**
   *
   * @param {object} options.context - ojet build context which contains useful fields like
   * buildType
   * @param {object} options.config - Default webpack config generated by ojet. You can
   * add to it, remove from it or update it using webpack-merge which was
   * installed alongside webpack. If desired, you can create your own config
   * and return it which will override the default config. Consider the examples below:
   *
   * 1. Adding a new plugin or optimization configuration into the default config:
   *
   *    config.plugins.push(new SomeWebpackPlugin());
   *
   *    config.optimization = {...config.optimization, splitChunks: { chunks: 'async' }};
   *
   *    config.output.publicPath = 'https://yourcdnlink.com/';
   *
   * 2. Alternatively, you can implement a custom config to override the default:
   *
   *    config = {};
   *
   *    config.plugins = [new SomeWebpackPlugin()];
   *
   *    config.optimization = {minimize: true, splitChunks: { chunks: 'all' }};
   *
   *    config.module.rules.push({test: /\.css$/, use: ['style-loader', 'css-loader']});
   *
   *    config.devServer = {static: {directory: path.join(_dirname, 'web')}, hot: true, port: 9000};
   *
   * @returns {object|undefined}
   */
  webpack: ({ context, config }) => {
    if (context.buildType === 'release') {
      // update config with release / production options
    } else {
      // update config with development options
    }

    config.output = {
      ...(config.output || {}),
      publicPath: '/'
    };

    config.resolve = config.resolve || {};
    config.resolve.alias = {
      ...(config.resolve.alias || {}),
      css: path.resolve(__dirname, 'node_modules/require-css/css.js'),
      'ojs/_foo_': path.resolve(__dirname, 'src/webpack-empty-module.js'),
      'ojs/_foo_$': path.resolve(__dirname, 'src/webpack-empty-module.js')
    };

    config.module = config.module || {};
    config.module.rules = [
      ...(config.module.rules || []),
      {
        test: /\.json$/,
        type: 'javascript/auto'
      },
      {
        test: /\.js\.map$/,
        type: 'asset/source'
      },
      {
        test: /\.cur$/,
        type: 'asset/resource'
      }
    ];

    config.plugins = [
      ...(config.plugins || []),
      new webpack.IgnorePlugin({
        resourceRegExp: /\.js\.map$/
      }),
      new EnsureRedwoodThemeFirstPlugin(),
      new CopyWebpackPlugin({
        patterns: [
          {
            from: path.resolve(__dirname, 'src/404.html'),
            to: '404.html'
          }
        ]
      }),
      new webpack.NormalModuleReplacementPlugin(/^ojs\/_foo_$/, path.resolve(__dirname, 'src/webpack-empty-module.js'))
    ];

    const existingSetupMiddlewares = config.devServer && config.devServer.setupMiddlewares;

    const existingClient = (config.devServer && config.devServer.client) || {};
    const existingOverlay =
      existingClient.overlay && typeof existingClient.overlay === 'object'
        ? existingClient.overlay
        : {};

    config.devServer = {
      ...(config.devServer || {}),
      client: {
        ...existingClient,
        overlay: {
          ...existingOverlay,
          runtimeErrors: (error) => !isResizeObserverLoopError(error)
        }
      },
      setupMiddlewares: (middlewares, devServer) => {
        middlewares.unshift({
          name: 'nested-asset-rewrite',
          path: '/',
          middleware: (req, res, next) => {
            const assetMatch = req.url && req.url.match(/^\/(?:.+\/)?(styles|js)\/(.+)$/);
            if (assetMatch) {
              req.url = `/${assetMatch[1]}/${assetMatch[2]}`;
            }
            next();
          }
        });

        return existingSetupMiddlewares
          ? existingSetupMiddlewares(middlewares, devServer)
          : middlewares;
      },
      historyApiFallback: {
        disableDotRule: true,
        rewrites: [
          {
            from: /^\/(?:.+\/)?styles\/(.+)$/,
            to: ({ match }) => `/styles/${match[1]}`
          },
          {
            from: /^\/(?:.+\/)?js\/(.+)$/,
            to: ({ match }) => `/js/${match[1]}`
          },
          {
            from: /./,
            to: '/index.html'
          }
        ]
      }
    };

    // only have to return if new config object was created but
    // since it doesn't matter always returning the config is good
    // practice
    return { context, webpack: config };
  }
};
