import { h } from 'preact';

export const validatorsNumberRangeValidatorDescription = (
  <>
    <p>
      This demo shows how JET's NumberRangeValidator can be used with Oracle JET editable components.
    </p>

    <p>
      When the{' '}
      <code className={"prettyprint"}>min</code>{' '}
      and{' '}
      <code className={"prettyprint"}>max</code>{' '}
      attributes are specified on the input number component, an implicit NumberRangeValidator is
      created. This is different from any NumberRangeValidator present in the
      <code className={"prettyprint"}>validators</code>{' '}
      attribute.
    </p>

    <h2>Test Steps</h2>
    <ol>
      <li>
        To see the error text generated by NumberRangeValidator, enter an incorrect value. E.g., type
        "123" and tab off the field.
      </li>
      <li>Enter a number that falls in the expected range and tab off to clear the error.</li>
    </ol>
  </>
);
