import { h } from 'preact';
import type { ComponentProps } from 'preact';
import { useMemo, useState } from 'preact/hooks';
import { IntlDateTimeConverter } from 'ojs/ojconverter-datetime';
import AsyncDateRestrictionValidator = require('ojs/ojasyncvalidator-daterestriction');
import 'ojs/ojdatetimepicker';
import 'ojs/ojformlayout';
import 'ojs/ojinputtext';

type InputDateValue = string | undefined;
type InputTextValue = ComponentProps<'oj-input-text'>['value'];
type InputTextChangedEvent = Parameters<
  NonNullable<ComponentProps<'oj-input-text'>['onvalueChanged']>
>[0];
type InputDateChangedEvent = Parameters<
  NonNullable<ComponentProps<'oj-input-date'>['onvalueChanged']>
>[0];

type HolidayMeta = {
  disabled: true;
  tooltip: string;
  className: string;
};

const HOLIDAYS: Record<number, Record<number, HolidayMeta>> = {
  1: {
    7: { disabled: true, tooltip: 'Not Going To Take It Anymore Day!', className: 'holiday' },
    10: { disabled: true, tooltip: 'Cut Your Energy Costs Day!', className: 'holiday' },
    16: { disabled: true, tooltip: 'Nothing Day!', className: 'holiday' }
  },
  2: {
    10: { disabled: true, tooltip: 'Clean Out Your Computer Day!', className: 'holiday' },
    17: { disabled: true, tooltip: 'My Way Day!', className: 'holiday' }
  },
  3: {
    11: { disabled: true, tooltip: 'Organize Your Home Office Day!', className: 'holiday' }
  },
  4: {
    3: { disabled: true, tooltip: 'World Party Day!', className: 'holiday' },
    29: { disabled: true, tooltip: 'One Day Without Shoes Day!', className: 'holiday' }
  },
  5: {
    19: { disabled: true, tooltip: 'May (Sunshine) Ray Day!', className: 'holiday' }
  },
  6: {
    13: { disabled: true, tooltip: 'Blame Someone Else Day!', className: 'holiday' },
    29: { disabled: true, tooltip: 'International Picnic Day!', className: 'holiday' }
  },
  7: {
    2: { disabled: true, tooltip: 'I Forgot Day!', className: 'holiday' },
    22: { disabled: true, tooltip: 'Hammock Day!', className: 'holiday' }
  },
  8: {
    2: { disabled: true, tooltip: 'Relaxation Day!', className: 'holiday' },
    22: { disabled: true, tooltip: 'Individual Rights Day!', className: 'holiday' }
  },
  10: {
    7: { disabled: true, tooltip: 'Relax in a Bathtub Day!', className: 'holiday' }
  },
  11: {
    17: { disabled: true, tooltip: 'Take A Hike Day!', className: 'holiday' }
  }
};

export const ValidatorsDateRestrictionValidator = () => {
  const [dateValue1, setDateValue1] = useState<InputTextValue>('March 31, 2014');
  const [dateValue2, setDateValue2] = useState<InputDateValue>('');
  const [dateValue3, setDateValue3] = useState<InputDateValue>('');
  const [cannotWorkHelpInstruction, setCannotWorkHelpInstruction] = useState('Pick any date');

  const datetimeConverter = useMemo(
    () =>
      new IntlDateTimeConverter({
        formatType: 'date',
        dateFormat: 'long'
      }),
    []
  );

  const validators = useMemo(
    () => [
      new AsyncDateRestrictionValidator({
        dayFormatter: (dateInfo: { month: number; date: number }) => {
          if (dateInfo.month === 4 && dateInfo.date === 1) {
            return { disabled: true };
          }
          return null;
        },
        messageSummary: "You can't fool me! Try a different date."
      })
    ],
    []
  );

  const workingDaysFormatter = useMemo(
    () => (dateInfo: { month: number; date: number }) => {
      const metadata = HOLIDAYS[dateInfo.month]?.[dateInfo.date];
      if (metadata?.disabled && metadata.tooltip) {
        setCannotWorkHelpInstruction(`Can't work on this day because it's ${metadata.tooltip}`);
        return metadata;
      }

      setCannotWorkHelpInstruction('Pick any date');
      return metadata ?? null;
    },
    []
  );

  const handleTextDateChanged = (event: InputTextChangedEvent) => {
    setDateValue1(event.detail.value ?? '');
  };

  const handleDate2Changed = (event: InputDateChangedEvent) => {
    setDateValue2(event.detail.value ?? undefined);
  };

  const handleDate3Changed = (event: InputDateChangedEvent) => {
    setDateValue3(event.detail.value ?? undefined);
  };

  return (
    <div id="validator-example">
      <h3 class="oj-header-border">Using 'validators' attribute</h3>
      Both examples restrict entering or selecting a date that falls on April Fools. These examples
      explicitly set the DateRestrictionValidator using the validators attribute. You cannot affect the
      date styling this way, however, so April Fools day is not disabled in the calendar. To see the
      error generated by DateRestrictionValidator enter or select a date that falls on April 01. E.g.,
      type "04-01-14" and tab off the field.
      <p></p>
      <oj-form-layout>
        <oj-input-text
          id="foolsErrand1"
          value={dateValue1}
          onvalueChanged={handleTextDateChanged}
          help={{ instruction: 'Enter any date, just not April Fools Day' }}
          converter={datetimeConverter}
          validators={validators}
          labelHint="input text"
        />
        <oj-input-date
          id="foolsErrand3"
          value={dateValue2}
          onvalueChanged={handleDate2Changed}
          help={{ instruction: 'Pick any date, just not April Fools Day' }}
          validators={validators}
          labelHint="input date"
        />
      </oj-form-layout>
      <h3 class="oj-header-border">Default DateRestrictionValidator created by input date</h3>
      Both examples restrict entering or selecting a date that is marked as a special holiday. You can
      affect the date styling using the day-formatter or day-meta-data attributes, so the restricted
      dates are shown as disabled and cannot be picked from the calendar.
      <ul>
        <li>Open the datepicker and notice the restricted dates are disabled.</li>
        <li>Type in a restricted date and tab off the field.</li>
        <li>
          Notice the field shows an error message. You can customize it using the translations
          attribute. The input date components automatically restrict selection of date values that are
          restricted.
        </li>
        <li>Select a valid date from the picker and tab off to clear error.</li>
      </ul>
      <p></p>
      <oj-form-layout>
        <oj-input-date
          id="workdays1"
          value={dateValue3}
          onvalueChanged={handleDate3Changed}
          help={{ instruction: cannotWorkHelpInstruction }}
          dayFormatter={workingDaysFormatter}
          labelHint="input date (using 'day-formatter')"
          translations={{
            dateRestriction: {
              messageDetail: 'translations attribute: Do not choose a disabled date.'
            }
          }}
        />
      </oj-form-layout>
    </div>
  );
};

export default ValidatorsDateRestrictionValidator;
