import { h } from 'preact';

export const validatorsDateTimeRangeValidatorDescription = (
  <>
    <p>
      This demo shows how JET&apos;s DateTimeRangeValidator can be used with Oracle JET date and time
      components.
    </p>
    <p>
      When the{' '}
      <code className={"prettyprint"}>min</code>{' '}
      and{' '}
      <code className={"prettyprint"}>max</code>{' '}
      attributes are specified on the input date and time components, an implicit DateTimeRangeValidator
      is created. You can also set an explicit DateTimeRangeValidator using the
      <code className={"prettyprint"}>validators</code>{' '}
      attribute. This demo shows both approaches.
    </p>
    <h2>Test Steps</h2>
    <ol>
      <li>
        To see the error text generated by DateTimeRangeValidator, enter an incorrect value. For
        example, type "12-12-99" and tab off the field.
      </li>
      <li>
        The input date components automatically restrict selection of date values that fall outside the
        range.
      </li>
      <li>
        Enter a date that falls in the current millennium and is less than today&apos;s date and tab off
        to clear the error.
      </li>
    </ol>
  </>
);
