// @ts-nocheck
import { h } from 'preact';

export const tableColumnContentWrappingRecipe = (
  <>
    <ol>
      <li>Add columns with large text data generated by Lorem Ipsum.</li>
      <li>
        Set a className attribute for columns that need content wrapping by adding
        <code>oj-helper-overflow-wrap-anywhere oj-helper-white-space-normal</code>
      </li>
      <li>Optionally you can set horizontal alignment with oj-helper-text-align-*(start, center or end) classes for the column content as well as the headers. You can also set vertical alignment by setting vertical-align property in column style attribute.</li>
    </ol>
  </>
);
