import 'preact';

export const validatorsLengthValidatorDescription = (
  <>
    <p>
      This demo shows how JET's LengthValidator can be used with Oracle JET editable components using
      the{' '}
      <code className={"prettyprint"}>validators</code>{' '}
      property.
    </p>
    <p>
      The LengthValidator has a{' '}
      <code className={"prettyprint"}>countBy</code>{' '}
      option that takes one of two values:
    </p>
    <ul>
      <li>
        <code className={"prettyprint"}>'codeUnit'</code>{' '}
        - counts each UTF16 code unit. For Javascript Strings, this is equal to the length of the String
        and means that Unicode supplementary characters will be counted as two characters since they are
        represented by a surrogate pair of UTF16 code units.
      </li>
      <li>
        <code className={"prettyprint"}>'codePoint'</code>{' '}
        - counts each code point. Unicode supplementary characters will be counted as one character.
      </li>
    </ul>

    <h2>Test Steps</h2>
    <ol>
      <li>
        To see the error text generated by the LengthValidator, enter a value with less or more number
        of characters than what is expected. For example, type "1" and tab off the field.
      </li>
      <li>Enter a value with the expected number of characters and tab off to clear the error.</li>
      <li>
        Type in supplementary characters, like "𠲖", to test the{' '}
        <code className={"prettyprint"}>countBy</code>{' '}
        option.
      </li>
    </ol>
  </>
);
